// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJb2m6EgEtDrcamFPHtY_bGAthwnZdDHA',
    appId: '1:92237986655:web:e6f115cfb210376231d4ea',
    messagingSenderId: '92237986655',
    projectId: 'taller3-firebase-db08b',
    authDomain: 'taller3-firebase-db08b.firebaseapp.com',
    storageBucket: 'taller3-firebase-db08b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyjzXOu4zcV9vrEmegVMX-8u4MdouNnhQ',
    appId: '1:92237986655:android:4058c82dcd3c3ee831d4ea',
    messagingSenderId: '92237986655',
    projectId: 'taller3-firebase-db08b',
    storageBucket: 'taller3-firebase-db08b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaPTvrW98SHWNxXwiHPLdd8bNKzrBJVM',
    appId: '1:92237986655:ios:d5e6ed89f1a1063d31d4ea',
    messagingSenderId: '92237986655',
    projectId: 'taller3-firebase-db08b',
    storageBucket: 'taller3-firebase-db08b.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmaPTvrW98SHWNxXwiHPLdd8bNKzrBJVM',
    appId: '1:92237986655:ios:d5e6ed89f1a1063d31d4ea',
    messagingSenderId: '92237986655',
    projectId: 'taller3-firebase-db08b',
    storageBucket: 'taller3-firebase-db08b.firebasestorage.app',
    iosBundleId: 'com.example.parqueadero2025G2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJb2m6EgEtDrcamFPHtY_bGAthwnZdDHA',
    appId: '1:92237986655:web:420733e79038ca5531d4ea',
    messagingSenderId: '92237986655',
    projectId: 'taller3-firebase-db08b',
    authDomain: 'taller3-firebase-db08b.firebaseapp.com',
    storageBucket: 'taller3-firebase-db08b.firebasestorage.app',
  );
}
